services:
  mail_service:
      image: vivekdev01/mailer:1
      # build:
      #   context: .
      #   dockerfile: Dockerfile
      # command: uwsgi --socket 0.0.0.0:9000 --module mail:app --http-timeout 600  --processes 4 --threads 8
      command: python mail.py
      ports:
        - 9000:9000
      env_file:
        - .env


# docker-compose -p mailer down;
# docker build -t vivekdev01/mailer:1 .;
# docker-compose -p mailer up -d;
# docker logs -f mailer-mail_service-1;